[package]
name = "vpkParser"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.19", features = ["cargo"] }
regex = "1.11.0"

[profile.release]
strip = true
opt-level = "z"
panic = "abort"
